// Versão do sistema — atualize aqui a cada entrega (aparece no rodapé, na ajuda e nas planilhas exportadas)
const APP_VERSAO = { numero: '1.5.1', data: '10/09/2026', nome: 'Totali Antecipa', historico: [
  { v: '1.5.1', data: '10/09/2026', o: 'Busca no Portal Nacional direto do site (função na nuvem + API Gateway) liberada: certificado A1 guardado no login com senha cifrada. Quando a SEFAZ não entrega o XML (rejeição "fora de prazo", nota indisponível, sem resposta), o aviso traz o link do Portal Nacional da NF-e e um atalho "consultar" por nota, que copia a chave e abre o portal para a consulta manual.' },
  { v: '1.5.0', data: '09/09/2026', o: 'Certificado A1 guardado no login do usuário (arquivo .pfx no Firestore, só o dono lê; a senha fica só no computador, protegida pelo Windows): em qualquer máquina com o INICIAR.bat o sistema usa o arquivo do login e pede só a senha. No site, aviso claro de que a busca no Portal Nacional é só na versão local. Repositório renomeado para totali-antecipa.' },
  { v: '1.4.1', data: '09/09/2026', o: 'E-mail de novo usuário com botões Aceitar / Recusar (link abre o sistema e conclui a ação); e-mails @totalicontabilidade.com.br viram administradores após verificar o e-mail; contador de pedidos pendentes no menu Usuários; envio de e-mail sem plano pago via Google Apps Script (server/email-apps-script.gs).' },
  { v: '1.4.0', data: '09/09/2026', o: 'Login com e-mail e senha e banco de dados na nuvem (Firebase Authentication + Firestore): empresas, regras, parâmetros, apurações e XMLs compartilhados entre os usuários autorizados. Novo usuário cria o login e fica aguardando; aviso automático para contato@totalicontabilidade.com.br com link para autorizar; tela Cadastros › Usuários para administradores. Publicado como site em totalicontabilidade.github.io/dia-certo.' },
  { v: '1.3.0', data: '09/09/2026', o: 'Planilha oficial do Portal Nacional da ST (SE, v0019) importada com MVA-ST por alíquota de origem, PFC, alíquota interna e FECOEP por CEST/NCM (materiais/st-se-portal.csv, conversor server/importar-portal-st.ps1); ficha do NCM e motor usam o Portal. Planilha de itens começa no nº do item. Validação Faro Tem (Simples): cosméticos 25% + FECOEP 2 pts, complementação com ST retida, escova dental com encerramento. Repositório git preparado para GitHub Pages.' },
  { v: '1.2.0', data: '09/09/2026', o: 'Base legal conferida no RICMS/SE oficial (PDF da SEFAZ baixado): cesta básica do art. 40 § 3º com 3,6%/2,1% do art. 787, MVA de suínos (Dec. 756/2024), contribuinte suspenso 30% (art. 786), FECOEP fora da antecipação sem encerramento (art. 616-C-A), códigos do DAE (Portaria 390/2016), prazos (Portaria 600/2023). CNAEs da Receita no cadastro da empresa com sugestão de finalidade (revenda, uso/consumo, imobilizado) por item. Busca no texto do RICMS e documentos oficiais em Materiais de apoio.' },
  { v: '1.1.0', data: '09/09/2026', o: 'Validado com a Mais Barato (regime normal, cesta básica optante): cesta 3,6% e 2,1% (30% × carga 12%/7%), FECOEP só nas receitas com encerramento no regime normal, uso/consumo fora do DIA, espelho com partes com/sem encerramento somadas, notas adiadas e "já recolhida no DIFAL", planilha ST/SE em modo aviso, aviso de notas não importadas, identificação de regime e cesta optante pelo espelho, documentos de apoio.' },
  { v: '1.0.0', data: '09/09/2026', o: 'Primeira versão: espelho do DIA + XML, motor do Mapa da SEFAZ/SE (receitas 2607/2631/2674/2445), FECOEP, exportação Excel (mapa, itens, FECOEP, resumo, conferência), busca no Portal Nacional da NF-e com certificado A1 (Distribuição DF-e + ciência), materiais de apoio do Fiscal Certo, identificação de regime pela Receita Federal.' },
] };
